services:

  redis:
    image: redis:7-alpine
    container_name: server-scanner-redis

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    command: redis-server --appendonly yes

    restart: unless-stopped


  postgres:
    image: postgres:17-alpine
    container_name: server-scanner-postgres

    environment:
      POSTGRES_USER: scanner
      POSTGRES_PASSWORD: scanner
      POSTGRES_DB: server_scanner

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    restart: unless-stopped


volumes:
  redis-data:
  postgres-data: